name: Build DEV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker login
        run: |
          docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push amd64 Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }} --platform linux/amd64 --secret id=SUPABASE_URL,src=${{ secrets.SUPABASE_URL }} --secret id=SUPABASE_KEY,src=${{ secrets.SUPABASE_KEY }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }}
      
      - name: Build and push arm64 Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }} --platform linux/arm64 --secret id=SUPABASE_URL,src=${{ secrets.SUPABASE_URL }} --secret id=SUPABASE_KEY,src=${{ secrets.SUPABASE_KEY }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }}