name: Build DEV

on:
  workflow_dispatch:
  
jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        secret_id: [SUPABASE_URL, SUPABASE_KEY]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker login
        run: |
          docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASS }}
      
      - name: Build and push Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }} \
            --platform ${{ matrix.platform }} \
            $(for id in "${{ matrix.secret_id }}"; do echo "--secret id=$id,src=${{ secrets.$id }}"; done)
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }}