name: Build DEV

on:
  workflow_dispatch:


jobs:
  push-image-to-docker-hub:
    runs-on: ubuntu-latest  
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
SECRETS
      
      - name: Build  Docker image
        run: |
          docker build . \
            --file Dockerfile \
            --tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }} \
            --platform ${{ matrix.platform }} \
            --secret id=.env,src=.env
        
      
      - name: Docker login
        run: |
          docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASS }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_TAG_DEV }}
